### ISSUE TITLE
Consider upgrading to simdjson 0.2.0

### ISSUE THREAD

**Issue by lemire** [microsoft/FishStore#11]
The library simdjson has a new major release (0.2.0). Major changes:

* Support for 64-bit ARM processors, can run under iOS (iPhone).
* Runtime dispatching on x64 processors (switches to SSE on older x64 processors, uses AVX2 when available). Supports processors as far back as the Intel Westmere.
* More accurate number parsing.
* Fixes most warnings under Visual Studio.
* Several small bugs have been fixed.
* Better performance in some cases.
* Introduces a JSON Pointer interface https://tools.ietf.org/html/rfc6901
* Better and more specific error messages (with optional textual descriptions).
* valgrind clean.
* Unified code style (LLVM).

**Comment by Skyprophet** [comment]
Thanks Daniel. Will recently start working on it!

**Comment by Skyprophet** [comment]
Done. Please refer to #12
