### ISSUE TITLE
This project was never built using Visual Studio 2019

### ISSUE THREAD

**Issue by DBJDBJ** [microsoft/FishStore#14]
Would it not be useful to do that and put the fishstore.sln in some subdirectory?
As we all know: "He who uses CMake, he likes pain" ...

There are also C++03 (or is it 98?) constructs in here ... but that is another big subject ...

Please advise ...

**Comment by Skyprophet** [comment]
I am able to build with CMake with following commands:

```
mkdir build
cd build
cmake -G "Visual Studio 16 2019" ..
```

Then you will get the sln file. The whole project should be a subject of C++17.

We use CMake so that we can support both Linux and Windows across different compiler version.

@badrishc What do you think, should we put a sln file inside the project.

**Comment by DBJDBJ** [comment]
Many thanks for replying. 

I might be so bold to talk here about project prominence. 
Popularity among  "ordinary programmers" ... not experts or WG21 committee members, for example.
This is a very interesting project for the people building business apps, who are not snazzy c++ library builders. The entry bar is high for them. They have never used CMake and never will. A lot of them are C# coders, etc, etc ...

(detour: Document titled "Why we did this", might also be immensely helpful to people who are still doing data layers with OLEDB, perhaps)

If I am not mistaken project benefactors are selling Visual Studio 2019 too :)
Just place the VS 2019 project in here and reap the benefits ...?
Also, a detailed and friendly explanation on how to build using Visual Code will be very welcome.
And then from that angle you can nicely explain how to build on nix, using VS Code + Extensions

Kind regards ...

**Comment by DBJDBJ** [comment]
`cmake -G "Visual Studio 16 2019" ..` ?

Again allow me to make a mistake, but I think the latest cmake + VS2019 requires -A for architecture?
For example:

`cmake  -A ''x86' -G "Visual Studio 16 2019" ..` ?

![image](https://snipboard.io/m5lp6X.jpg)

This is what I am talking about :) "civilians" will just look elsewhere ...

**Comment by Skyprophet** [comment]
On my side, it is okay just leave `-A` as default. My understanding is cmake will generate solution files based on the default architecture on your platform.

Of course if you want any other target, you can specify explicitly.

Dong
On 12/6/2019 02:17:00, dbj <notifications@github.com> wrote:
cmake -G "Visual Studio 16 2019" .. ?
Again allow me to make a mistake, but I think the latest cmake + VS2019 requires -A for architecture?
For example:
cmake -A ''x86' -G "Visual Studio 16 2019" .. ?
[image] [https://camo.githubusercontent.com/aa88e4e93bb5a7e06ebe08dbe7c5c8ab62e7e90e/68747470733a2f2f736e6970626f6172642e696f2f6d356c7036582e6a7067]
This is what I am talking about :) "civilians" will just look elsewhere ...

**Comment by DBJDBJ** [comment]
"On my side, it is okay just leave `-A` as default" .. After 30 years of C/C++ I do not know what do you mean by that :)  

I have built this, but as far as I remember I had to dig into CMake and then dig into what argument -A should have and then I was able to build with  -A "x86" ... Now Imagine , friendly C# people trying to build this?

Please at least add the cmake usage for VS2019 situations...

**Comment by DBJDBJ** [comment]
The correct command is:

```
cmake .. -G "Visual Studio 16 2019"
```

**Comment by Skyprophet** [comment]
Yeah, that's how I build it. Well, I mean by default `-A` is set to current platform. I will add that in README.

**Comment by DBJDBJ** [comment]
How to build using Visual Code editor will be also (methinks) immensely popular too ..
